"""FastAPI application for AI-powered Q&A with local LLaMA support.

This module provides two endpoints:
- POST /ask: Returns full answer as JSON
- POST /ask_stream: Streams tokens in real-time as plain text

Dependencies:
- fastapi: Web framework for building APIs
- pydantic: Data validation and serialization
- openai: OpenAI client (initialized but currently unused)
- localllama: Local LLaMA integration module
"""

import os
from dotenv import load_dotenv
from fastapi import FastAPI
from pydantic import BaseModel
from openai import OpenAI

from .localllama import stream, stream_tokens
from fastapi.responses import StreamingResponse

# Load environment variables from .env file
load_dotenv()

# Initialize OpenAI client (for potential future use with OpenAI APIs)
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# Create FastAPI application instance
app = FastAPI()

class Ask(BaseModel):
    """Request model for AI questions.
    
    Attributes:
        question: The user's question to be answered by the LLM
    """
    question: str


@app.post("/ask")
def ask(req: Ask):
    """Handle question requests and return complete answer as JSON.
    
    This endpoint streams tokens from the local LLaMA model but returns
    the full concatenated response as a single JSON object. Useful for
    applications that need the complete answer before processing.
    
    Args:
        req: Ask object containing the user's question
        
    Returns:
        dict: Contains "answer" key with the full generated text
    """
    # Stream tokens from LLaMA and collect into a single string
    resp = stream(req.question)
    return {"answer": resp}


@app.post("/ask_stream")
def ask_stream(req: Ask):
    """Handle question requests with real-time token streaming.
    
    This endpoint streams individual tokens as they are generated by the
    local LLaMA model. Useful for real-time UI updates and lower latency
    user experience. Use curl -N flag or accept streaming responses.
    
    Args:
        req: Ask object containing the user's question
        
    Returns:
        StreamingResponse: Streams plain text tokens in real-time
        
    Example:
        curl -N -X POST http://localhost:8000/ask_stream \\
          -H "Content-Type: application/json" \\
          -d '{"question": "Explain quantum computing"}'
    """
    # Return streaming response with tokens generated in real-time
    return StreamingResponse(stream_tokens(req.question), media_type="text/plain")
